apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-mock-data-generator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "senzing-mock-data-generator.name" . }}
    helm.sh/chart: {{ include "senzing-mock-data-generator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-mock-data-generator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-mock-data-generator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "SENZING_SUBCOMMAND"
              value: "url-to-kafka"
            - name: "SENZING_KAFKA_BOOTSTRAP_SERVER"
              value: "senzing-kafka-kafka:9092"
            - name: "SENZING_KAFKA_TOPIC"
              value: "senzing-kafka-topic"
            - name: "SENZING_INPUT_URL"
              value: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
            - name: "SENZING_RECORD_MAX"
              value: "10000"
            - name: "SENZING_RECORD_MONITOR"
              value: "100"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
