apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "senzing-mock-data-generator.fullname" . }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "SENZING_SUBCOMMAND"
              value: "{{ .Values.senzing.subcommand }}"
            - name: "SENZING_KAFKA_BOOTSTRAP_SERVER"
              value: "{{ .Values.senzing.kafkaBootstrapServerHost }}:{{ .Values.senzing.kafkaBootstrapServerPort }}"
            - name: "SENZING_KAFKA_TOPIC"
              value: "{{ .Values.senzing.kafkaTopic }}"
            - name: "SENZING_INPUT_URL"
              value: "{{ .Values.senzing.inputUrl }}"
            - name: "SENZING_RECORD_MAX"
              value: "{{ .Values.senzing.recordMax }}"
            - name: "SENZING_RECORD_MONITOR"
              value: "{{ .Values.senzing.recordMonitor }}"
