image:
  registry: docker.io
  repository: bitnami/phpmyadmin
  tag: 4.8.5
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
db:
  port: 3306
  bundleTestDB: false
ingress:
  enabled: false
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  tls: []
probesEnabled: true
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
